export const REASON_LABELS = {
    '4837': 'FRAUDULENT TRANSACTION NO CARDHOLDER AUTH',
    '10.4': 'OTHER FRAUD-CARD ABSENT ENVIRONMENT',
    '4853': 'CARDHOLDER DISPUTES',
    '13.1': 'MERCHANDISE/SERVICES NOT RECEIVED',
}

export const dashboardSummary = {
    scopeLabel: 'All 4 stores shown',
    productionCount: 170,
    metrics: [
        { key: 'total', label: 'TOTAL CHARGEBACKS', amount: 443.18, cases: 8, accent: 'emerald' },
        { key: 'receipts_pending', label: 'RECEIPTS NOT UPLOADED', amount: 63.29, cases: 2, accent: 'orange' },
        { key: 'in_dispute', label: 'IN DISPUTE / SUBMITTED', amount: 265.19, cases: 3, accent: 'purple' },
        { key: 'credit_recovered', label: 'CREDIT RECOVERED', amount: 31.88, cases: 1, accent: 'green' },
        { key: 'expired_lost', label: 'EXPIRED / LOST', amount: 82.82, cases: 2, subLabel: '1 expired', accent: 'red' },
        { key: 'uploaded_late', label: 'UPLOADED LATE', amount: null, cases: 1, casesOnly: true, accent: 'blue' },
    ],
    amountByStatus: [
        { label: 'Chargeback Received', count: 1, amount: 19.99, color: 'bg-blue-500' },
        { label: 'Receipt Pending', count: null, amount: 43.30, color: 'bg-orange-500' },
        { label: 'Completed', count: null, amount: 105.94, color: 'bg-emerald-500' },
        { label: 'Completed (Late)', count: null, amount: 92.15, color: 'bg-orange-600' },
        { label: 'Submitted to Processor', count: null, amount: 67.10, color: 'bg-purple-500' },
        { label: 'Credit Recovered', count: null, amount: 31.88, color: 'bg-lime-500' },
        { label: 'Chargeback Lost', count: null, amount: 58.45, color: 'bg-red-500' },
        { label: 'Expired — Past Due', count: null, amount: 24.37, color: 'bg-red-700' },
    ],
    pendingReceipts: [
        {
            id: 1,
            case_number: '9928932718',
            reference_number: 'CB-1003',
            store_name: 'PAPA JOHNS #5352',
            reason_code: '10.4',
            amount: 43.30,
            card_network: 'Visa',
            card_last_four: '3281',
            chargeback_received_date: '2026-06-10',
            processor_due_date: '2026-06-30',
            status: 'Receipt Pending',
            status_tone: 'warning',
            due_label: 'due in 5d',
        },
        {
            id: 2,
            case_number: '8847123901',
            reference_number: 'CB-1004',
            store_name: 'PAPA JOHNS #4821',
            reason_code: '13.1',
            amount: 19.99,
            card_network: 'Mastercard',
            card_last_four: '9042',
            chargeback_received_date: '2026-06-12',
            processor_due_date: '2026-07-02',
            status: 'Chargeback Received',
            status_tone: 'info',
            due_label: 'due in 7d',
        },
    ],
}
