<?php

namespace App\Models\DataEntry;

use App\Models\Settings\Company;
use App\Models\Traits\LogsActivity;
use App\Support\AuthorizedCompanies;
use App\Support\Filterable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PayrollJournal extends Model
{
    use HasFactory, Filterable, AuthorizedCompanies, LogsActivity;

    protected $table = 'payroll_journals';

    /**
     * Columns summed for DC food-labour reports (replaces legacy total_earnings).
     * Excludes hours (worked hours / units) and direct deposit routing amounts.
     */
    public const FLM_LABOUR_SUM_COLUMNS = [
        'bonus',
        'cs_accident',
        'cs_term_life',
        'crit_illness',
        'dental_a',
        'dental_b',
        'dental_d',
        'ee_term_life',
        'hospital_ind',
        'id_theft',
        'legal',
        'life_ltc',
        'pet_Well',
        'sp_term_life',
        'std',
        'vision',
        'cash_tips',
        'charge_tips',
        'charge_tips_reimb',
        'deduction',
        'dental',
        'wages',
        'medical',
        'mileage_reimb',
        'min_wage_adjust',
        'min_wage_adjust_anne',
        'min_wage_adjust_bcit',
        'min_wage_adjust_balt',
        'min_wage_adjust_calv',
        'min_wage_adjust_carr',
        'min_wage_adjust_char',
        'min_wage_adjust_fred',
        'min_wage_adjust_harf',
        'min_wage_adjust_howa',
        'min_wage_adjust_mont',
        'min_wage_adjust_prin',
        'min_wage_adjust_stma',
        'overtime',
        'overtime_wages',
        'px_garnishment',
        'px_garnishment_2',
        'retro_pretax_premium',
        'salary',
        'sick',
        'term_life_pretax',
        'vacation',

        'ee_withholdings',
        'er_withholdings',
        'manual_net_pay',
        'negotiable_net_pay',
        'non_negotiable_net_pay',
    ];

    protected $fillable = [
        'company_id',
        'eow',
        'bonus',
        'cs_accident',
        'cs_term_life',
        'crit_illness',
        'dental_a',
        'dental_b',
        'dental_d',
        'ee_term_life',
        'hospital_ind',
        'id_theft',
        'legal',
        'life_ltc',
        'pet_Well',
        'sp_term_life',
        'std',
        'vision',
        'cash_tips',
        'charge_tips',
        'charge_tips_reimb',
        'deduction',
        'dental',
        'direct_deposit_debit',
        'hours',
        'wages',
        'medical',
        'mileage_reimb',
        'min_wage_adjust',
        'min_wage_adjust_anne',
        'min_wage_adjust_bcit',
        'min_wage_adjust_balt',
        'min_wage_adjust_calv',
        'min_wage_adjust_carr',
        'min_wage_adjust_char',
        'min_wage_adjust_fred',
        'min_wage_adjust_harf',
        'min_wage_adjust_howa',
        'min_wage_adjust_mont',
        'min_wage_adjust_prin',
        'min_wage_adjust_stma',
        'overtime',
        'overtime_wages',
        'px_garnishment',
        'px_garnishment_2',
        'retro_pretax_premium',
        'salary',
        'sick',
        'term_life_pretax',
        'vacation',
        'ee_withholdings',
        'er_withholdings',
        'manual_net_pay',
        'negotiable_net_pay',
        'non_negotiable_net_pay',
        'ctc',
    ];

    protected $activityFields = [
        ['field' => 'company_id', 'label' => 'Store', 'table' => 'company', 'table_field' => 'name', 'type' => 'lookup'],
        ['field' => 'eow', 'label' => 'Eow', 'type' => 'string'],
        ['field' => 'bonus', 'label' => 'Bonus', 'type' => 'string'],
        ['field' => 'cs_accident', 'label' => 'Cs Accident', 'type' => 'string'],
        ['field' => 'cs_term_life', 'label' => 'Cs Term Life', 'type' => 'string'],
        ['field' => 'crit_illness', 'label' => 'Crit Illness', 'type' => 'string'],
        ['field' => 'dental_a', 'label' => 'Dental A', 'type' => 'string'],
        ['field' => 'dental_b', 'label' => 'Dental B', 'type' => 'string'],
        ['field' => 'dental_d', 'label' => 'Dental D', 'type' => 'string'],
        ['field' => 'ee_term_life', 'label' => 'Ee Term Life', 'type' => 'string'],
        ['field' => 'hospital_ind', 'label' => 'Hospital Ind', 'type' => 'string'],
        ['field' => 'id_theft', 'label' => 'Id Theft', 'type' => 'string'],
        ['field' => 'legal', 'label' => 'Legal', 'type' => 'string'],
        ['field' => 'life_ltc', 'label' => 'Life Ltc', 'type' => 'string'],
        ['field' => 'pet_Well', 'label' => 'Pet Well', 'type' => 'string'],
        ['field' => 'sp_term_life', 'label' => 'Sp Term Life', 'type' => 'string'],
        ['field' => 'std', 'label' => 'Std', 'type' => 'string'],
        ['field' => 'vision', 'label' => 'Vision', 'type' => 'boolean'],
        ['field' => 'cash_tips', 'label' => 'Cash Tips', 'type' => 'number'],
        ['field' => 'charge_tips', 'label' => 'Charge Tips', 'type' => 'number'],
        ['field' => 'charge_tips_reimb', 'label' => 'Charge Tips Reimb', 'type' => 'number'],
        ['field' => 'deduction', 'label' => 'Deduction', 'type' => 'string'],
        ['field' => 'dental', 'label' => 'Dental', 'type' => 'boolean'],
        ['field' => 'direct_deposit_debit', 'label' => 'Direct Deposit Debit', 'type' => 'string'],
        ['field' => 'hours', 'label' => 'Hours', 'type' => 'number'],
        ['field' => 'wages', 'label' => 'Wages', 'type' => 'string'],
        ['field' => 'medical', 'label' => 'Medical', 'type' => 'string'],
        ['field' => 'mileage_reimb', 'label' => 'Mileage Reimb', 'type' => 'number'],
        ['field' => 'min_wage_adjust', 'label' => 'Min Wage Adjust', 'type' => 'string'],
        ['field' => 'min_wage_adjust_anne', 'label' => 'Min Wage Adjust Anne', 'type' => 'string'],
        ['field' => 'min_wage_adjust_bcit', 'label' => 'Min Wage Adjust Bcit', 'type' => 'string'],
        ['field' => 'min_wage_adjust_balt', 'label' => 'Min Wage Adjust Balt', 'type' => 'string'],
        ['field' => 'min_wage_adjust_calv', 'label' => 'Min Wage Adjust Calv', 'type' => 'string'],
        ['field' => 'min_wage_adjust_carr', 'label' => 'Min Wage Adjust Carr', 'type' => 'string'],
        ['field' => 'min_wage_adjust_char', 'label' => 'Min Wage Adjust Char', 'type' => 'string'],
        ['field' => 'min_wage_adjust_fred', 'label' => 'Min Wage Adjust Fred', 'type' => 'string'],
        ['field' => 'min_wage_adjust_harf', 'label' => 'Min Wage Adjust Harf', 'type' => 'string'],
        ['field' => 'min_wage_adjust_howa', 'label' => 'Min Wage Adjust Howa', 'type' => 'string'],
        ['field' => 'min_wage_adjust_mont', 'label' => 'Min Wage Adjust Mont', 'type' => 'string'],
        ['field' => 'min_wage_adjust_prin', 'label' => 'Min Wage Adjust Prin', 'type' => 'string'],
        ['field' => 'min_wage_adjust_stma', 'label' => 'Min Wage Adjust Stma', 'type' => 'string'],
        ['field' => 'overtime', 'label' => 'Overtime', 'type' => 'string'],
        ['field' => 'overtime_wages', 'label' => 'Overtime Wages', 'type' => 'string'],
        ['field' => 'px_garnishment', 'label' => 'Px Garnishment', 'type' => 'string'],
        ['field' => 'px_garnishment_2', 'label' => 'Px Garnishment 2', 'type' => 'string'],
        ['field' => 'retro_pretax_premium', 'label' => 'Retro Pretax Premium', 'type' => 'string'],
        ['field' => 'salary', 'label' => 'Salary', 'type' => 'number'],
        ['field' => 'sick', 'label' => 'Sick', 'type' => 'string'],
        ['field' => 'term_life_pretax', 'label' => 'Term Life Pretax', 'type' => 'string'],
        ['field' => 'vacation', 'label' => 'Vacation', 'type' => 'string'],
        ['field' => 'ee_withholdings', 'label' => 'Ee Withholdings', 'type' => 'string'],
        ['field' => 'er_withholdings', 'label' => 'Er Withholdings', 'type' => 'string'],
        ['field' => 'manual_net_pay', 'label' => 'Manual Net Pay', 'type' => 'number'],
        ['field' => 'negotiable_net_pay', 'label' => 'Negotiable Net Pay', 'type' => 'number'],
        ['field' => 'non_negotiable_net_pay', 'label' => 'Non Negotiable Net Pay', 'type' => 'number'],
        ['field' => 'ctc', 'label' => 'Ctc', 'type' => 'string'],
        ['field' => 'count', 'label' => 'Count', 'type' => 'number'],
        ['field' => 'date_from', 'label' => 'Date From', 'type' => 'date'],
        ['field' => 'date_to', 'label' => 'Date To', 'type' => 'date'],
        ['field' => 'dates', 'label' => 'Dates', 'type' => 'array'],
        ['field' => 'filename', 'label' => 'Filename', 'type' => 'string'],
        ['field' => 'source', 'label' => 'Source', 'type' => 'string'],
        ['field' => 'imported_at', 'label' => 'Imported At', 'type' => 'string'],
        ['field' => 'ids', 'label' => 'Record IDs', 'type' => 'array'],
    ];

    protected $casts = [
        'company_id' => 'integer',
        'eow' => 'date',
        'bonus' => 'decimal:2',
        'cs_accident' => 'decimal:2',
        'cs_term_life' => 'decimal:2',
        'crit_illness' => 'decimal:2',
        'dental_a' => 'decimal:2',
        'dental_b' => 'decimal:2',
        'dental_d' => 'decimal:2',
        'ee_term_life' => 'decimal:2',
        'hospital_ind' => 'decimal:2',
        'id_theft' => 'decimal:2',
        'legal' => 'decimal:2',
        'life_ltc' => 'decimal:2',
        'pet_Well' => 'decimal:2',
        'sp_term_life' => 'decimal:2',
        'std' => 'decimal:2',
        'vision' => 'decimal:2',
        'cash_tips' => 'decimal:2',
        'charge_tips' => 'decimal:2',
        'charge_tips_reimb' => 'decimal:2',
        'deduction' => 'decimal:2',
        'dental' => 'decimal:2',
        'direct_deposit_debit' => 'decimal:2',
        'hours' => 'decimal:2',
        'wages' => 'decimal:2',
        'medical' => 'decimal:2',
        'mileage_reimb' => 'decimal:2',
        'min_wage_adjust' => 'decimal:2',
        'min_wage_adjust_anne' => 'decimal:2',
        'min_wage_adjust_bcit' => 'decimal:2',
        'min_wage_adjust_balt' => 'decimal:2',
        'min_wage_adjust_calv' => 'decimal:2',
        'min_wage_adjust_carr' => 'decimal:2',
        'min_wage_adjust_char' => 'decimal:2',
        'min_wage_adjust_fred' => 'decimal:2',
        'min_wage_adjust_harf' => 'decimal:2',
        'min_wage_adjust_howa' => 'decimal:2',
        'min_wage_adjust_mont' => 'decimal:2',
        'min_wage_adjust_prin' => 'decimal:2',
        'min_wage_adjust_stma' => 'decimal:2',
        'overtime' => 'decimal:2',
        'overtime_wages' => 'decimal:2',
        'px_garnishment' => 'decimal:2',
        'px_garnishment_2' => 'decimal:2',
        'retro_pretax_premium' => 'decimal:2',
        'salary' => 'decimal:2',
        'sick' => 'decimal:2',
        'term_life_pretax' => 'decimal:2',
        'vacation' => 'decimal:2',
        'ee_withholdings' => 'decimal:2',
        'er_withholdings' => 'decimal:2',
        'manual_net_pay' => 'decimal:2',
        'negotiable_net_pay' => 'decimal:2',
        'non_negotiable_net_pay' => 'decimal:2',
        'ctc' => 'decimal:2',
    ];

    protected $sortable = [
        'eow',
        'bonus',
        'created_at',
        'ctc',
        'total_earnings',
        'total_tips',
        'er_withholdings',
    ];

    protected $searchable = [
        'eow',
        'created_at',
        'bonus',
        'ctc',
        'total_earnings',
        'total_tips',
        'er_withholdings',
    ];

    protected $allowedFilters = [
        'eow',
        'created_at',
        'updated_at',
        'bonus',
        'ctc',
        'total_earnings',
        'total_tips',
        'er_withholdings',
    ];

    public static function flmLabourSumSqlExpression(?string $table = null): string
    {
        $table = $table ?? (new static)->getTable();
        $parts = [];
        foreach (self::FLM_LABOUR_SUM_COLUMNS as $column) {
            $parts[] = "COALESCE(`{$table}`.`{$column}`, 0)";
        }

        return implode(' + ', $parts);
    }

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id')
            ->selectRaw('id, CONCAT(store_number, " - ", name) as name, store_number,state_id');
    }
}
